In [2]:
import pandas as pd

#TASK1

In [4]:
population=pd.read_csv('/content/population.csv')
population

           country  population
0    United States   331002651
1            China  1411778724
2            India  1380004385
3            Japan   125836021
4          Germany    83240525
5   United Kingdom    67886011
6           France    65273511
7            Italy    60461826
8           Canada    38005238
9        Australia    25687041
10          Brazil   212559417
11          Russia   145934462
12     South Korea    51780579
13           Spain    46754778
14          Mexico   128932753
15       Indonesia   273523615
16    Saudi Arabia    34813871
17          Turkey    84339067
18    South Africa    59308690
19       Argentina    45195774
20     Netherlands    17441139
21     Switzerland     8654622
22          Sweden    10353442
23          Norway     5421241
24       Singapore     5850342

In [5]:
population.head()

         country  population
0  United States   331002651
1          China  1411778724
2          India  1380004385
3          Japan   125836021
4        Germany    83240525

In [6]:
population.shape

(25, 2)

In [7]:
population.dtypes

country       object
population     int64
dtype: object

#TASK2

In [8]:
gdp=pd.read_excel('/content/gdp.xlsx')
gdp

           Country       GDP
0    United States  30500000
1            China  19230000
2            India   4187000
3            Japan   4180000
4          Germany   4744000
5   United Kingdom   3839000
6           France   3211000
7            Italy   2420000
8           Canada   2250000
9        Australia   1880000
10          Brazil   2330000
11          Russia   2200000
12     South Korea   1800000
13           Spain   1710000
14          Mexico   1810000
15       Indonesia   1500000
16    Saudi Arabia   1100000
17          Turkey   1350000
18    South Africa    410000
19       Argentina    640000
20     Netherlands   1150000
21     Switzerland    940000
22          Sweden    650000
23          Norway    580000
24       Singapore    530000

In [9]:
gdp.columns

Index(['Country', 'GDP'], dtype='object')

In [10]:
gdp.dtypes

Country    object
GDP         int64
dtype: object

#TASK3

In [11]:
internet_users=pd.read_json('internet_users.json')
internet_users

           country  internet_users
0    United States       312000000
1            China      1080000000
2            India       850000000
3            Japan       118000000
4          Germany        79000000
5   United Kingdom        66000000
6           France        62000000
7            Italy        56000000
8           Canada        36000000
9        Australia        24000000
10          Brazil       181000000
11          Russia       125000000
12     South Korea        50000000
13           Spain        44000000
14          Mexico       102000000
15       Indonesia       212000000
16    Saudi Arabia        34000000
17          Turkey        69000000
18    South Africa        43000000
19       Argentina        41000000
20     Netherlands        17000000
21     Switzerland         8500000
22          Sweden        10100000
23          Norway         5300000
24       Singapore         5600000

In [12]:
internet_users = pd.DataFrame(internet_users)
internet_users

           country  internet_users
0    United States       312000000
1            China      1080000000
2            India       850000000
3            Japan       118000000
4          Germany        79000000
5   United Kingdom        66000000
6           France        62000000
7            Italy        56000000
8           Canada        36000000
9        Australia        24000000
10          Brazil       181000000
11          Russia       125000000
12     South Korea        50000000
13           Spain        44000000
14          Mexico       102000000
15       Indonesia       212000000
16    Saudi Arabia        34000000
17          Turkey        69000000
18    South Africa        43000000
19       Argentina        41000000
20     Netherlands        17000000
21     Switzerland         8500000
22          Sweden        10100000
23          Norway         5300000
24       Singapore         5600000

#TASK4

In [14]:
literacy_rate = pd.read_xml('literacy_rate.xml')
literacy_rate

              name  literacy_rate
0    United States           99.0
1            China           97.2
2            India           77.7
3            Japan           99.0
4          Germany           99.0
5   United Kingdom           99.0
6           France           99.0
7            Italy           99.0
8           Canada           99.0
9        Australia           99.0
10          Brazil           93.2
11          Russia           99.7
12     South Korea           98.8
13           Spain           98.6
14          Mexico           95.4
15       Indonesia           96.0
16    Saudi Arabia           97.3
17          Turkey           96.7
18    South Africa           95.0
19       Argentina           99.1
20     Netherlands           99.0
21     Switzerland           99.0
22          Sweden           99.0
23          Norway          100.0
24       Singapore           97.5

#TASK5

In [ ]:
# Explore each dataset.
# Find the following:
# ● Number of rows
# ● Number of columns
# ● Column names
# ● Data types
# ● Missing values
# ● Duplicate records

In [15]:
#population data set
population.info()
population.duplicated().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   country     25 non-null     object
 1   population  25 non-null     int64
dtypes: int64(1), object(1)
memory usage: 532.0+ bytes

np.int64(0)

In [16]:
#gdp data set
gdp.info()
gdp.duplicated().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Country  25 non-null     object
 1   GDP      25 non-null     int64
dtypes: int64(1), object(1)
memory usage: 532.0+ bytes

np.int64(0)

In [17]:
#internet user data set

internet_users.info()
internet_users.duplicated().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   country         25 non-null     object
 1   internet_users  25 non-null     int64
dtypes: int64(1), object(1)
memory usage: 532.0+ bytes

np.int64(0)

In [18]:
# literacy rate data set
literacy_rate.info()
literacy_rate.duplicated().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           25 non-null     object
 1   literacy_rate  25 non-null     float64
dtypes: float64(1), object(1)
memory usage: 532.0+ bytes

np.int64(0)

#TASK6

In [19]:
population.rename(columns={'Country': 'country'}, inplace=True)
gdp.rename(columns={'Country': 'country'}, inplace=True)
internet_users.rename(columns={'Country': 'country'}, inplace=True)
literacy_rate.rename(columns={'name': 'country'}, inplace=True)

In [20]:
population.columns

Index(['country', 'population'], dtype='object')

In [21]:
gdp.columns

Index(['country', 'GDP'], dtype='object')

In [22]:
internet_users.columns

Index(['country', 'internet_users'], dtype='object')

In [23]:
literacy_rate.columns

Index(['country', 'literacy_rate'], dtype='object')

#TASK7

In [24]:
population['population'] = pd.to_numeric(population['population'])

In [25]:
gdp['GDP'] = pd.to_numeric(gdp['GDP'])

In [26]:
internet_users['internet_users'] = pd.to_numeric(internet_users['internet_users'])

In [27]:
literacy_rate['literacy_rate'] = pd.to_numeric(literacy_rate['literacy_rate'])

In [28]:
population.dtypes

country       object
population     int64
dtype: object

In [30]:
gdp.dtypes

country    object
GDP         int64
dtype: object

In [31]:
internet_users.dtypes

country           object
internet_users     int64
dtype: object

In [32]:
literacy_rate.dtypes

country           object
literacy_rate    float64
dtype: object

#TASK8

In [33]:
merged_df = pd.merge(
    population,
    gdp,
    on='country',
    how='inner'
)

In [34]:
merged_df = pd.merge(
    merged_df,
    internet_users,
    on='country',
    how='inner'
)

In [35]:
literacy_rate = pd.read_xml('/content/literacy_rate.xml')
literacy_rate.rename(columns={'name': 'country'}, inplace=True)

merged_df = pd.merge(
    merged_df,
    literacy_rate,
    on='country',
    how='inner'
)

In [36]:
merged_df

           country  population       GDP  internet_users  literacy_rate
0    United States   331002651  30500000       312000000           99.0
1            China  1411778724  19230000      1080000000           97.2
2            India  1380004385   4187000       850000000           77.7
3            Japan   125836021   4180000       118000000           99.0
4          Germany    83240525   4744000        79000000           99.0
5   United Kingdom    67886011   3839000        66000000           99.0
6           France    65273511   3211000        62000000           99.0
7            Italy    60461826   2420000        56000000           99.0
8           Canada    38005238   2250000        36000000           99.0
9        Australia    25687041   1880000        24000000           99.0
10          Brazil   212559417   2330000       181000000           93.2
11          Russia   145934462   2200000       125000000           99.7
12     South Korea    51780579   1800000        50000000           98.8
13           Spain    46754778   1710000        44000000           98.6
14          Mexico   128932753   1810000       102000000           95.4
15       Indonesia   273523615   1500000       212000000           96.0
16    Saudi Arabia    34813871   1100000        34000000           97.3
17          Turkey    84339067   1350000        69000000           96.7
18    South Africa    59308690    410000        43000000           95.0
19       Argentina    45195774    640000        41000000           99.1
20     Netherlands    17441139   1150000        17000000           99.0
21     Switzerland     8654622    940000         8500000           99.0
22          Sweden    10353442    650000        10100000           99.0
23          Norway     5421241    580000         5300000          100.0
24       Singapore     5850342    530000         5600000           97.5

In [37]:
merged_df.columns

Index(['country', 'population', 'GDP', 'internet_users', 'literacy_rate'], dtype='object')

#TASK9

In [39]:
merged_df['Internet Penetration (%)'] = (
    merged_df['internet_users'] / merged_df['population']
) * 100

In [40]:
merged_df['GDP Per Capita'] = (
    merged_df['GDP'] / merged_df['population']
)

In [41]:
merged_df['Internet Penetration (%)'].round(2)

0     94.26
1     76.50
2     61.59
3     93.77
4     94.91
5     97.22
6     94.98
7     92.62
8     94.72
9     93.43
10    85.15
11    85.65
12    96.56
13    94.11
14    79.11
15    77.51
16    97.66
17    81.81
18    72.50
19    90.72
20    97.47
21    98.21
22    97.55
23    97.76
24    95.72
Name: Internet Penetration (%), dtype: float64

In [42]:
merged_df['GDP Per Capita'].round(2)

0     0.09
1     0.01
2     0.00
3     0.03
4     0.06
5     0.06
6     0.05
7     0.04
8     0.06
9     0.07
10    0.01
11    0.02
12    0.03
13    0.04
14    0.01
15    0.01
16    0.03
17    0.02
18    0.01
19    0.01
20    0.07
21    0.11
22    0.06
23    0.11
24    0.09
Name: GDP Per Capita, dtype: float64

In [43]:
merged_df[
        ['country', 'population', 'GDP', 'internet_users',
         'literacy_rate', 'Internet Penetration (%)', 'GDP Per Capita']
    ].head()

,country,population,GDP,internet_users,literacy_rate,Internet Penetration (%),GDP Per Capita
0,United States,331002651,30500000,312000000,99.0,94.259064,0.092144
1,China,1411778724,19230000,1080000000,97.2,76.499240,0.013621
2,India,1380004385,4187000,850000000,77.7,61.594007,0.003034
3,Japan,125836021,4180000,118000000,99.0,93.772832,0.033218
4,Germany,83240525,4744000,79000000,99.0,94.905696,0.056991

#TASK10

In [44]:
import sqlite3

conn = sqlite3.connect('country_statistics.db')
merged_df.to_sql('country_statistics', conn)

25

##TASK11

In [46]:
q = "SELECT * FROM country_statistics LIMIT 5"
db = pd.read_sql_query(q, conn)

db

,index,country,population,GDP,internet_users,literacy_rate,Internet Penetration (%),GDP Per Capita
0,0,United States,331002651,30500000,312000000,99.0,94.259064,0.092144
1,1,China,1411778724,19230000,1080000000,97.2,76.499240,0.013621
2,2,India,1380004385,4187000,850000000,77.7,61.594007,0.003034
3,3,Japan,125836021,4180000,118000000,99.0,93.772832,0.033218
4,4,Germany,83240525,4744000,79000000,99.0,94.905696,0.056991

##PART-E

In [47]:
print("6. Top 5 countries by GDP per capita:")
print(merged_df.nlargest(5, 'GDP Per Capita')[['country', 'GDP Per Capita']])
print("\n")

print("7. Total population represented in the dataset:")
print(merged_df['population'].sum())
print("\n")

print("8. Average internet penetration across all countries:")
print(merged_df['Internet Penetration (%)'].mean())
print("\n")

print("9. Country having the highest number of internet users:")
print(merged_df.loc[merged_df['internet_users'].idxmax()][['country', 'internet_users']])
print("\n")

print("10. Correlation between Literacy Rate and Internet Penetration:")
print(merged_df['literacy_rate'].corr(merged_df['Internet Penetration (%)']))

6. Top 5 countries by GDP per capita:
          country  GDP Per Capita
21    Switzerland        0.108612
23         Norway        0.106987
0   United States        0.092144
24      Singapore        0.090593
9       Australia        0.073189


7. Total population represented in the dataset:
4720039725


8. Average internet penetration across all countries:
89.6609210897238


9. Country having the highest number of internet users:
country                China
internet_users    1080000000
Name: 1, dtype: object


10. Correlation between Literacy Rate and Internet Penetration:
0.7727536531179539

In [48]:
# 1. Top 5 countries by GDP

merged_df.nlargest(5, 'GDP')[['country', 'GDP']]

         country       GDP
0  United States  30500000
1          China  19230000
4        Germany   4744000
2          India   4187000
3          Japan   4180000

In [49]:
# 2. List the Top 5 countries by population.
merged_df.nlargest(5, 'population')[['country', 'population']]

          country  population
1           China  1411778724
2           India  1380004385
0   United States   331002651
15      Indonesia   273523615
10         Brazil   212559417

In [50]:
# 3. Average literacy rate
merged_df['literacy_rate'].mean()

np.float64(97.248)

In [51]:
# 4. Countries with literacy rate greater than 90%:
merged_df[merged_df['literacy_rate'] > 90][['country', 'literacy_rate']]

           country  literacy_rate
0    United States           99.0
1            China           97.2
3            Japan           99.0
4          Germany           99.0
5   United Kingdom           99.0
6           France           99.0
7            Italy           99.0
8           Canada           99.0
9        Australia           99.0
10          Brazil           93.2
11          Russia           99.7
12     South Korea           98.8
13           Spain           98.6
14          Mexico           95.4
15       Indonesia           96.0
16    Saudi Arabia           97.3
17          Turkey           96.7
18    South Africa           95.0
19       Argentina           99.1
20     Netherlands           99.0
21     Switzerland           99.0
22          Sweden           99.0
23          Norway          100.0
24       Singapore           97.5

In [52]:
# 5. Countries with internet penetration greater than 70%
merged_df[merged_df['Internet Penetration (%)'] > 70][['country', 'Internet Penetration (%)']]

           country  Internet Penetration (%)
0    United States                 94.259064
1            China                 76.499240
3            Japan                 93.772832
4          Germany                 94.905696
5   United Kingdom                 97.221797
6           France                 94.984932
7            Italy                 92.620425
8           Canada                 94.723785
9        Australia                 93.432326
10          Brazil                 85.152661
11          Russia                 85.654888
12     South Korea                 96.561300
13           Spain                 94.108029
14          Mexico                 79.111008
15       Indonesia                 77.507019
16    Saudi Arabia                 97.662222
17          Turkey                 81.812620
18    South Africa                 72.502023
19       Argentina                 90.716446
20     Netherlands                 97.470698
21     Switzerland                 98.213417
22          Sweden                 97.552099
23          Norway                 97.763593
24       Singapore                 95.720900

In [53]:
# 6. Top 5 countries by GDP per capita
merged_df.nlargest(5, 'GDP Per Capita')[['country', 'GDP Per Capita']]

          country  GDP Per Capita
21    Switzerland        0.108612
23         Norway        0.106987
0   United States        0.092144
24      Singapore        0.090593
9       Australia        0.073189

In [54]:
# 7. Total population represented in the dataset
merged_df['population'].sum()

np.int64(4720039725)

In [55]:
# 8. Average internet penetration across all countries

merged_df['Internet Penetration (%)'].mean()

np.float64(89.6609210897238)

In [56]:
# 9. Country having the highest number of internet users

merged_df.loc[merged_df['internet_users'].idxmax()][['country', 'internet_users']]

country                China
internet_users    1080000000
Name: 1, dtype: object

In [57]:
# 10. Correlation between Literacy Rate and Internet Penetration

merged_df['literacy_rate'].corr(merged_df['Internet Penetration (%)'])

np.float64(0.7727536531179539)

In [58]:
# 11. Display the Top 5 countries by GDP:
q = "SELECT country, GDP FROM country_statistics ORDER BY GDP DESC LIMIT 5"
df = pd.read_sql_query(q, conn)
print(df)
print("\n")

         country       GDP
0  United States  30500000
1          China  19230000
2        Germany   4744000
3          India   4187000
4          Japan   4180000

In [59]:
# 12. Find the average literacy rate:
q= "SELECT AVG(literacy_rate) FROM country_statistics"
df = pd.read_sql_query(q, conn)
print(df.iloc[0,0])
print("\n")

97.24799999999999

In [60]:
# 13. Display all countries having literacy rate above 90%:
q= "SELECT country, literacy_rate FROM country_statistics WHERE literacy_rate > 90 ORDER BY literacy_rate DESC"
df= pd.read_sql_query(q, conn)
print(df)
print("\n")

           country  literacy_rate
0           Norway          100.0
1           Russia           99.7
2        Argentina           99.1
3    United States           99.0
4            Japan           99.0
5          Germany           99.0
6   United Kingdom           99.0
7           France           99.0
8            Italy           99.0
9           Canada           99.0
10       Australia           99.0
11     Netherlands           99.0
12     Switzerland           99.0
13          Sweden           99.0
14     South Korea           98.8
15           Spain           98.6
16       Singapore           97.5
17    Saudi Arabia           97.3
18           China           97.2
19          Turkey           96.7
20       Indonesia           96.0
21          Mexico           95.4
22    South Africa           95.0
23          Brazil           93.2

In [61]:
# 14. Find the Top 5 countries with the highest internet penetration:
q= "SELECT country, \"Internet Penetration (%)\" FROM country_statistics ORDER BY \"Internet Penetration (%)\" DESC LIMIT 5"
df = pd.read_sql_query(q, conn)
print(df)
print("\n")

        country  Internet Penetration (%)
0   Switzerland                 98.213417
1        Norway                 97.763593
2  Saudi Arabia                 97.662222
3        Sweden                 97.552099
4   Netherlands                 97.470698

In [62]:
# 15. Calculate the total population:
q= "SELECT SUM(population) FROM country_statistics"
df = pd.read_sql_query(q, conn)
print(df.iloc[0,0])
print("\n")

4720039725

In [63]:
# 16. Find the country with the highest GDP per capita:
q = "SELECT country, \"GDP Per Capita\" FROM country_statistics ORDER BY \"GDP Per Capita\" DESC LIMIT 1"
df_highest_gdp_per_capita = pd.read_sql_query(q, conn)
print(df_highest_gdp_per_capita)
print("\n")

       country  GDP Per Capita
0  Switzerland        0.108612

In [64]:
# 17. Export the final merged dataset as a CSV file.

final_df = pd.read_sql_query("SELECT * FROM country_statistics", conn)
final_df.to_csv('country_statistics.csv', index=False)
print("Dataset exported to 'country_statistics.csv'.")
print("\n")

Dataset exported to 'country_statistics.csv'.

In [65]:
# 18. Sort the dataset in descending order of GDP per Capita and display the Top 10 countries.
q = "SELECT country, \"GDP Per Capita\" FROM country_statistics ORDER BY \"GDP Per Capita\" DESC LIMIT 10"
df_top10_gdp_per_capita = pd.read_sql_query(q, conn)
print(df_top10_gdp_per_capita)
print("\n")

          country  GDP Per Capita
0     Switzerland        0.108612
1          Norway        0.106987
2   United States        0.092144
3       Singapore        0.090593
4       Australia        0.073189
5     Netherlands        0.065936
6          Sweden        0.062781
7          Canada        0.059202
8         Germany        0.056991
9  United Kingdom        0.056551

In [66]:
# Close the connection
conn.close()