In [ ]:
import numpy as np
import pandas as pd

In [ ]:
auto_data=pd.read_csv("/content/moive.csv")

In [ ]:
auto_data.head()

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0

In [ ]:
auto_data.shape

(1000, 12)

In [ ]:
auto_data.columns

Index(['Rank', 'Title', 'Genre', 'Description', 'Director', 'Actors', 'Year',
       'Runtime (Minutes)', 'Rating', 'Votes', 'Revenue (Millions)',
       'Metascore'],
      dtype='object')

In [ ]:
auto_data.dtypes

Rank                    int64
Title                  object
Genre                  object
Description            object
Director               object
Actors                 object
Year                    int64
Runtime (Minutes)       int64
Rating                float64
Votes                   int64
Revenue (Millions)    float64
Metascore             float64
dtype: object

In [ ]:
auto_data.isnull()

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False,False,False,True,False
996,False,False,False,False,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False,False,False,True,False
999,False,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
auto_data.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Length: 1000, dtype: bool

In [ ]:
auto_data.drop_duplicates()

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0
...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Secret in Their Eyes,"Crime,Drama,Mystery","A tight-knit team of rising investigators, alo...",Billy Ray,"Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...",2015,111,6.2,27585,NaN,45.0
996,997,Hostel: Part II,Horror,Three American college students studying abroa...,Eli Roth,"Lauren German, Heather Matarazzo, Bijou Philli...",2007,94,5.5,73152,17.54,46.0
997,998,Step Up 2: The Streets,"Drama,Music,Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008,98,6.2,70699,58.01,50.0
998,999,Search Party,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,NaN,22.0
999,1000,Nine Lives,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.64,11.0

In [ ]:
auto_data.rename(columns={'Title': 'Movie_Title'}, inplace=True)

In [ ]:
auto_data

,Rank,Movie_Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0
...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Secret in Their Eyes,"Crime,Drama,Mystery","A tight-knit team of rising investigators, alo...",Billy Ray,"Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...",2015,111,6.2,27585,NaN,45.0
996,997,Hostel: Part II,Horror,Three American college students studying abroa...,Eli Roth,"Lauren German, Heather Matarazzo, Bijou Philli...",2007,94,5.5,73152,17.54,46.0
997,998,Step Up 2: The Streets,"Drama,Music,Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008,98,6.2,70699,58.01,50.0
998,999,Search Party,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,NaN,22.0
999,1000,Nine Lives,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.64,11.0

In [ ]:
auto_data['Genre'].unique()

array(['Action,Adventure,Sci-Fi', 'Adventure,Mystery,Sci-Fi',
       'Horror,Thriller', 'Animation,Comedy,Family',
       'Action,Adventure,Fantasy', 'Comedy,Drama,Music', 'Comedy',
       'Action,Adventure,Biography', 'Adventure,Drama,Romance',
       'Adventure,Family,Fantasy', 'Biography,Drama,History',
       'Animation,Adventure,Comedy', 'Action,Comedy,Drama',
       'Action,Thriller', 'Biography,Drama', 'Drama,Mystery,Sci-Fi',
       'Adventure,Drama,Thriller', 'Drama', 'Crime,Drama,Horror',
       'Action,Adventure,Drama', 'Drama,Thriller',
       'Action,Adventure,Comedy', 'Action,Horror,Sci-Fi',
       'Adventure,Drama,Sci-Fi', 'Action,Adventure,Western',
       'Comedy,Drama', 'Horror', 'Adventure,Drama,Fantasy',
       'Action,Crime,Thriller', 'Action,Crime,Drama',
       'Adventure,Drama,History', 'Crime,Horror,Thriller',
       'Drama,Romance', 'Comedy,Drama,Romance', 'Horror,Mystery,Thriller',
       'Crime,Drama,Mystery', 'Drama,Romance,Thriller',
       'Drama,History,Thriller', 'Action,Drama,Thriller', 'Drama,History',
       'Action,Drama,Romance', 'Drama,Fantasy', 'Action,Sci-Fi',
       'Adventure,Drama,War', 'Action,Comedy,Fantasy',
       'Biography,Comedy,Crime', 'Crime,Drama', 'Comedy,Crime,Drama',
       'Action,Comedy,Crime', 'Animation,Drama,Fantasy',
       'Horror,Mystery,Sci-Fi', 'Drama,Mystery,Thriller',
       'Crime,Drama,Thriller', 'Biography,Crime,Drama',
       'Crime,Mystery,Thriller', 'Action,Horror,Thriller',
       'Romance,Sci-Fi', 'Action,Fantasy,War', 'Action,Biography,Drama',
       'Drama,Horror,Mystery', 'Adventure,Drama,Family',
       'Adventure,Comedy,Romance', 'Action', 'Adventure,Crime,Mystery',
       'Comedy,Family,Musical', 'Adventure,Comedy,Drama',
       'Drama,Horror,Thriller', 'Drama,Music', 'Mystery,Thriller',
       'Mystery,Thriller,Western', 'Comedy,Family',
       'Biography,Comedy,Drama', 'Drama,Western', 'Drama,Mystery,Romance',
       'Action,Drama,Mystery', 'Action,Adventure,Crime',
       'Adventure,Sci-Fi,Thriller', 'Action,Comedy,Mystery',
       'Thriller,War', 'Action,Adventure,Thriller',
       'Drama,Fantasy,Romance', 'Action,Drama,History',
       'Animation,Adventure,Family', 'Adventure,Horror',
       'Drama,Romance,Sci-Fi', 'Action,Adventure,Family', 'Action,Comedy',
       'Comedy,Romance', 'Horror,Mystery', 'Drama,Family,Fantasy',
       'Sci-Fi', 'Drama,War', 'Drama,Fantasy,Horror',
       'Crime,Drama,History', 'Horror,Sci-Fi,Thriller',
       'Action,Drama,Sport', 'Adventure,Biography,Drama',
       'Biography,Drama,Thriller', 'Action,Adventure,Mystery',
       'Drama,Horror', 'Comedy,Crime', 'Drama,Fantasy,War',
       'Action,Adventure,Romance', 'Action,Drama,War',
       'Drama,Musical,Romance', 'Drama,Sci-Fi,Thriller',
       'Action,Drama,Sci-Fi', 'Drama,Sci-Fi', 'Adventure,Fantasy',
       'Thriller', 'Biography,Drama,Romance', 'Action,Adventure',
       'Action,Fantasy', 'Action,Drama,Horror', 'Comedy,Music,Romance',
       'Biography,Drama,Sport', 'Action,Horror', 'Comedy,Horror,Thriller',
       'Crime,Drama,Music', 'Action,Sci-Fi,Thriller',
       'Drama,Horror,Sci-Fi', 'Drama,Sport', 'Comedy,Horror',
       'Comedy,Fantasy,Romance', 'Comedy,Fantasy', 'Comedy,Drama,Fantasy',
       'Adventure,Comedy,Horror', 'Comedy,Mystery',
       'Action,Mystery,Sci-Fi', 'Action,Crime,Fantasy',
       'Comedy,Fantasy,Horror', 'Animation,Action,Adventure',
       'Action,Comedy,Family', 'Comedy,Sci-Fi', 'Action,Biography,Crime',
       'Adventure,Comedy', 'Comedy,Music', 'Comedy,Drama,Horror',
       'Action,Horror,Romance', 'Action,Drama,Fantasy',
       'Action,Mystery,Thriller', 'Action,Adventure,Horror',
       'Animation,Family,Fantasy', 'Adventure,Horror,Mystery',
       'Action,Horror,Mystery', 'Adventure,Comedy,Family',
       'Action,Crime,Mystery', 'Comedy,Drama,Family',
       'Action,Crime,Sport', 'Mystery,Sci-Fi,Thriller', 'Sci-Fi,Thriller',
       'Adventure,Drama,Horror', 'Biography,History,Thriller',
       'Adventure,Comedy,Sci-Fi', 'Fantasy,Horror',
       'Action,Fantasy,Thriller', 'Comedy,Romance,Sport',
       'Animation,Action,Comedy', 'Drama,Fantasy,Thriller',
       'Action,Comedy,Romance', 'Action,Fantasy,Horror',
       'Mystery,Romance,Sci-Fi', 'Comedy,Drama,Thriller',
       'Comedy,Western', 'Drama,History,War', 'Fantasy,Horror,Thriller',
       'Drama,Horror,Musical', 'Drama,Family', 'Romance,Sci-Fi,Thriller',
       'Animation,Fantasy', 'Drama,Mystery,War', 'Action,Drama,Family',
       'Adventure,Drama,Western', 'Drama,Music,Romance',
       'Comedy,Romance,Western', 'Adventure,Drama', 'Drama,Thriller,War',
       'Drama,Fantasy,Mystery', 'Comedy,Crime,Thriller',
       'Animation,Comedy,Drama', 'Action,Comedy,Sci-Fi',
       'Drama,Romance,War', 'Adventure,Fantasy,Mystery',
       'Mystery,Romance,Thriller', 'Biography,Drama,Mystery',
       'Animation,Drama,Romance', 'Comedy,Horror,Romance',
       'Action,Thriller,War', 'Action,Comedy,Horror',
       'Action,Crime,Sci-Fi', 'Crime,Thriller', 'Comedy,Horror,Sci-Fi',
       'Crime,Drama,Fantasy', 'Drama,Fantasy,Music',
       'Action,Comedy,Sport', 'Fantasy,Mystery,Thriller', 'Adventure',
       'Adventure,Biography', 'Adventure,Biography,Crime',
       'Comedy,Drama,Musical', 'Comedy,Family,Romance',
       'Biography,Drama,Family', 'Drama,Fantasy,Musical',
       'Adventure,Family', 'Adventure,Comedy,Fantasy',
       'Drama,Family,Music', 'Comedy,Family,Fantasy'], dtype=object)

In [ ]:
auto_data['Genre'].value_counts()

Genre
Action,Adventure,Sci-Fi     50
Drama                       48
Comedy,Drama,Romance        35
Comedy                      32
Drama,Romance               31
                            ..
Drama,Fantasy,Musical        1
Adventure,Family             1
Adventure,Comedy,Fantasy     1
Drama,Family,Music           1
Comedy,Family,Fantasy        1
Name: count, Length: 207, dtype: int64

In [ ]:
auto_data['Revenue (Millions)'].isna()

0      False
1      False
2      False
3      False
4      False
       ...
995     True
996    False
997    False
998     True
999    False
Name: Revenue (Millions), Length: 1000, dtype: bool

In [ ]:
auto_data['Metascore'].isna()

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Name: Metascore, Length: 1000, dtype: bool

In [ ]:
top_5 = auto_data.sort_values(by='Rating', ascending=False).head(5)
print(top_5[['Movie_Title', 'Rating']])

          Movie_Title  Rating
54    The Dark Knight     9.0
80          Inception     8.8
117            Dangal     8.8
36       Interstellar     8.6
249  The Intouchables     8.6

In [ ]:
auto_data.sort_values(by='Revenue (Millions)', ascending=False).head(1)

,Rank,Movie_Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
50,51,Star Wars: Episode VII - The Force Awakens,"Action,Adventure,Fantasy",Three decades after the defeat of the Galactic...,J.J. Abrams,"Daisy Ridley, John Boyega, Oscar Isaac, Domhna...",2015,136,8.1,661608,936.63,81.0

In [ ]:
auto_data.sort_values(by='Revenue (Millions)', ascending=True).head(1)

,Rank,Movie_Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
231,232,A Kind of Murder,"Crime,Drama,Thriller","In 1960s New York, Walter Stackhouse is a succ...",Andy Goddard,"Patrick Wilson, Jessica Biel, Haley Bennett, V...",2016,95,5.2,3305,0.0,50.0

In [ ]:
avg_rating_by_director = auto_data.groupby('Director')['Rating'].mean().sort_values(ascending=False)
print("Average Rating by Director:\n", avg_rating_by_director.head())

Average Rating by Director:
 Director
Nitesh Tiwari                       8.80
Christopher Nolan                   8.68
Olivier Nakache                     8.60
Makoto Shinkai                      8.60
Florian Henckel von Donnersmarck    8.50
Name: Rating, dtype: float64

In [ ]:
movies_per_year = auto_data['Year'].value_counts().sort_index()
print("Movies per Year:\n", movies_per_year)

Movies per Year:
 Year
2006     44
2007     53
2008     52
2009     51
2010     60
2011     63
2012     64
2013     91
2014     98
2015    127
2016    297
Name: count, dtype: int64

In [ ]:
high_rated_high_revenue_movies = auto_data[(auto_data['Rating'] > 8) & (auto_data['Revenue (Millions)'] > 100)]
print("Movies with Rating > 8 and Revenue > 100M:\n")
print(high_rated_high_revenue_movies[['Movie_Title', 'Rating', 'Revenue (Millions)']])

Movies with Rating > 8 and Revenue > 100M:

                                      Movie_Title  Rating  Revenue (Millions)
0                         Guardians of the Galaxy     8.1              333.13
6                                      La La Land     8.3              151.06
36                                   Interstellar     8.6              187.99
50     Star Wars: Episode VII - The Force Awakens     8.1              936.63
54                                The Dark Knight     9.0              533.32
67                             Mad Max: Fury Road     8.1              153.63
74                                       Zootopia     8.1              341.26
76                                   The Avengers     8.1              623.28
77                           Inglourious Basterds     8.3              120.52
80                                      Inception     8.8              292.57
82                        The Wolf of Wall Street     8.2              116.87
83                                      Gone Girl     8.1              167.74
92                                       The Help     8.1              169.71
99                                   The Departed     8.5              132.37
114  Harry Potter and the Deathly Hallows: Part 2     8.1              380.96
124                         The Dark Knight Rises     8.5              448.13
138                                Shutter Island     8.1              127.97
144                              Django Unchained     8.4              162.80
241                                    Inside Out     8.2              356.45
427                          The Bourne Ultimatum     8.1              227.14
499                                            Up     8.3              292.98
634                                        WALL·E     8.4              223.81
645                                   Gran Torino     8.2              148.09
688                                   Toy Story 3     8.3              414.98
772                      How to Train Your Dragon     8.1              217.39

In [ ]:
director_stats = auto_data.groupby('Director').agg(
    avg_rating=('Rating', 'mean'),
    total_revenue=('Revenue (Millions)', 'sum')
).sort_values(by='avg_rating', ascending=False)

print("Director Statistics (Average Rating and Total Revenue):\n")
print(director_stats.head())

Director Statistics (Average Rating and Total Revenue):

                                  avg_rating  total_revenue
Director
Nitesh Tiwari                           8.80          11.15
Christopher Nolan                       8.68        1515.09
Olivier Nakache                         8.60          13.18
Makoto Shinkai                          8.60           4.68
Florian Henckel von Donnersmarck        8.50          11.28

In [ ]:
movies_by_year_stats = auto_data.groupby('Year').agg(
    movie_count=('Movie_Title', 'count'),
    avg_rating=('Rating', 'mean')
).sort_values(by='Year', ascending=True)

print("Movies by Year Statistics (Count and Average Rating):\n")
print(movies_by_year_stats)

Movies by Year Statistics (Count and Average Rating):

      movie_count  avg_rating
Year
2006           44    7.125000
2007           53    7.133962
2008           52    6.784615
2009           51    6.960784
2010           60    6.826667
2011           63    6.838095
2012           64    6.925000
2013           91    6.812088
2014           98    6.837755
2015          127    6.602362
2016          297    6.436700

In [ ]:
#Create a new column 'Profitability' (Revenue per minute)
auto_data['Profitability'] = auto_data['Revenue (Millions)'] / auto_data['Runtime (Minutes)']

# Find the top 10 most profitable movies
top_10_profitable_movies = auto_data.sort_values(by='Profitability', ascending=False).head(10)

print("Top 10 Most Profitable Movies (Revenue per Minute):\n")
print(top_10_profitable_movies[['Movie_Title', 'Profitability']])

Top 10 Most Profitable Movies (Revenue per Minute):

                                    Movie_Title  Profitability
50   Star Wars: Episode VII - The Force Awakens       6.886985
85                               Jurassic World       5.259516
119                                Finding Dory       5.013299
87                                       Avatar       4.694506
76                                 The Avengers       4.358601
15                      The Secret Life of Pets       4.233448
688                                 Toy Story 3       4.028932
12                                    Rogue One       4.001278
174                                      Frozen       3.928824
797                             Despicable Me 2       3.755612

In [ ]:
# Define the conditions for categorization
conditions = [
    (auto_data['Rating'] < 6),
    (auto_data['Rating'] >= 6) & (auto_data['Rating'] < 7.5),
    (auto_data['Rating'] >= 7.5)
]

# Define the corresponding categories
choices = ['Poor', 'Average', 'Excellent']

# Create the new 'Rating_Category' column
auto_data['Rating_Category'] = np.select(conditions, choices, default='Unknown')

# Display the count of movies in each category
print("Distribution of movies by Rating Category:\n")
print(auto_data['Rating_Category'].value_counts())

Distribution of movies by Rating Category:

Rating_Category
Average      586
Excellent    230
Poor         184
Name: count, dtype: int64

###Custom Movie Scoring Function
I will now create a custom function to calculate a 'Movie_Score' for each movie based on its 'Rating' and 'Revenue (Millions)' using the formula: Rating * 10 + Revenue (Millions). This function will then be applied to the DataFrame to create a new column.

In [ ]:
def calculate_movie_score(row):
    # Ensure 'Revenue (Millions)' is treated as 0 if NaN for scoring purposes
    revenue = row['Revenue (Millions)'] if pd.notna(row['Revenue (Millions)']) else 0
    return (row['Rating'] * 10) + revenue

# Apply the custom function to create the 'Movie_Score' column
auto_data['Movie_Score'] = auto_data.apply(calculate_movie_score, axis=1)

# Display the top 10 movies based on this new score
print("Top 10 Movies by Custom Score:\n")
print(auto_data[['Movie_Title', 'Rating', 'Revenue (Millions)', 'Movie_Score']].sort_values(by='Movie_Score', ascending=False).head(10))

Top 10 Movies by Custom Score:

                                    Movie_Title  Rating  Revenue (Millions)  \
50   Star Wars: Episode VII - The Force Awakens     8.1              936.63
87                                       Avatar     7.8              760.51
85                               Jurassic World     7.0              652.18
76                                 The Avengers     8.1              623.28
54                              The Dark Knight     9.0              533.32
12                                    Rogue One     7.9              532.17
119                                Finding Dory     7.4              486.29
124                       The Dark Knight Rises     8.5              448.13
94                      Avengers: Age of Ultron     7.4              458.99
578             The Hunger Games: Catching Fire     7.6              424.65

     Movie_Score
50       1017.63
87        838.51
85        722.18
76        704.28
54        623.32
12        611.17
119       560.29
124       533.13
94        532.99
578       500.65